[metadata]
name = "html"
description = "A channel to select HTML files"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f -t l -e html -H -I"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
# shortcut = "f1"
