[metadata]
name = "media"
description = "A channel to select media"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f -t l -e mov -e mp4 -e m4a -e mp3 -e wav -e aac -e opus -H -I"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
# shortcut = "f1"
