[metadata]
name = "typst"
description = "A channel to select typst files"
requirements = ["fd", "bat"]

[source]
# command = ["fd -t f -e pdf", "fd -t f -e -H"]
command = ["fd -t f -t l -e typ -H -I"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
# shortcut = "f1"
