# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: "  âžœ  "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# anchor: bottom
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 100
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
# namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "m"
    desc: "Message"
    submenu:
      - key: "d"
        desc: Discord
        cmd: uwsm app -- discord
      - key: "t"
        desc: Telegram
        cmd: uwsm app -- Telegram
      - key: "s"
        desc: Signal
        cmd: uwsm app -- signal-desktop

  - key: "w"
    desc: Window
    submenu:
      - key: "f"
        desc: Fullscreen
        cmd: hyprctl dispatch fullscreen
      - key: "c"
        desc: Center Window
        cmd: hyprctl dispatch centerwindow
      - key: "o"
        desc: Orient (Toggle Split)
        cmd: hyprctl dispatch togglesplit
      - key: "m"
        desc: Move
        submenu:
          - key: "h"
            desc: Move Left
            cmd: hyprctl dispatch moveactive -100 0
            keep_open: true
          - key: "l"
            desc: Move Right
            cmd: hyprctl dispatch moveactive 100 0
            keep_open: true
          - key: "k"
            desc: Move Up
            cmd: hyprctl dispatch moveactive 0 -100
            keep_open: true
          - key: "j"
            desc: Move Down
            cmd: hyprctl dispatch moveactive 0 100
            keep_open: true
      - key: "r"
        desc: Resize
        submenu:
          - key: "h"
            desc: Decrease Width
            cmd: hyprctl dispatch resizeactive -100 0
            keep_open: true
          - key: "l"
            desc: Increase Width
            cmd: hyprctl dispatch resizeactive 100 0
            keep_open: true
          - key: "k"
            desc: Decrease Height
            cmd: hyprctl dispatch resizeactive 0 -100
            keep_open: true
          - key: "j"
            desc: Increase Height
            cmd: hyprctl dispatch resizeactive 0 100
            keep_open: true

  - key: "p"
    desc: Player
    submenu:
      - key: "p"
        desc: Previous
        cmd: playerctl previous
      - key: "t"
        desc: Toggle
        cmd: playerctl play-pause
      - key: "n"
        desc: Next
        cmd: playerctl next
